### ISSUE TITLE
graphLab

### ISSUE THREAD

**Issue by korkile** [dataquestio/ds-containers#4]
Hey, can you add graphLab support?

**Comment by jaypeedevlin** [comment]
Based off a quick look [here](https://turi.com/download/install-graphlab-create-command-line.html) it seems like we wouldn't integrate this because licenses are required.

There's nothing to stop you from `docker exec`'ing into the container though and installing it yourself.

See the section 'installing more packages' here: https://www.dataquest.io/blog/docker-data-science/
